### ISSUE TITLE
java.util.regex.PatternSyntaxException:  Look-behind pattern matches must have a bounded maximum length near index 9

### ISSUE THREAD

**Issue by scorpionhiccup** [twitter/twitter-korean-text#114]
On running the Twitter Korean Text, I'm getting the error:

` Look-behind pattern matches must have a bounded maximum length near index 9

((?<=\s+)|(?=\s+))

                 ^
     at java.util.regex.Pattern.compileImpl(Native Method)

     at java.util.regex.Pattern.compile(Pattern.java:1340)

     at java.util.regex.Pattern.<init>(Pattern.java:1324)

     at java.util.regex.Pattern.compile(Pattern.java:946)

     at java.lang.String.split(String.java:2325)

     at java.lang.String.split(String.java:2367)

     at com.twitter.penguin.korean.tokenizer.KoreanChunker$.chunk(KoreanChunker.scala:150)

     at com.twitter.penguin.korean.tokenizer.KoreanTokenizer$.tokenize(KoreanTokenizer.scala:96)

     at com.twitter.penguin.korean.TwitterKoreanProcessor$.tokenize(TwitterKoreanProcessor.scala:49)

     at com.twitter.penguin.korean.TwitterKoreanProcessor.tokenize(TwitterKoreanProcessor.scala)
` 

This is on running the example Java code of twitter Korean with stemming and normalization. 

Running via JDK1.7

Any help would be greatly appreciated.

**Comment by nlpenguin** [comment]
Are you running this on Android?

**Comment by scorpionhiccup** [comment]
Yes. I'm making a library using Java, creating a JAR and then using it as a library in Android.

**Comment by nlpenguin** [comment]
The line number seems to be incorrect, what's your open-korean-text version?

https://stackoverflow.com/questions/24256204/unknown-look-behind-group-near-index-in-java

This is using a syntax that Java 7 or higher support. I know you said you were running it via JDK 1.7, but there's a chance that you're actually executing your code with a Java6 JRE.

**Comment by scorpionhiccup** [comment]
I checked the build path in eclipse, and it is showing JDK 1.7 only. Is there anywhere else I should be checking?

**Comment by nlpenguin** [comment]
Hmm, what's the open-korean-text version you're importing in your maven pom.xml? Can you try it with the latest version and give me the stack trace? 

`at com.twitter.penguin.korean.tokenizer.KoreanChunker$.chunk(KoreanChunker.scala:150)` does have any regex to fix.

Anyways, it seems to be the API compatibility issue of Android Java. We may need to provide an extra parameter in the scala code to provide a "bounded maximum length".

**Comment by nlpenguin** [comment]
The latest version is `korean-text-4.4.4`

**Comment by gopi1410** [comment]
@scorpionhiccup did you solve this?
