### ISSUE TITLE
[Bug] tokenization solutions is sometimes empty.

### ISSUE THREAD

**Issue by nlpenguin** [twitter/twitter-korean-text#79]
This was thrown in a scalding job:

Caused by: java.lang.UnsupportedOperationException: empty.minBy
        at scala.collection.TraversableOnce$class.minBy(TraversableOnce.scala:252)
        at scala.collection.AbstractTraversable.minBy(Traversable.scala:104)
        at com.twitter.penguin.korean.v2.tokenizer.KoreanTokenizer$.com$twitter$penguin$korean$v2$tokenizer$KoreanTokenizer$$parseKoreanChunk(KoreanTokenizer.scala:244)
        at com.twitter.penguin.korean.v2.tokenizer.KoreanTokenizer$$anonfun$tokenize$1.apply(KoreanTokenizer.scala:257)
        at com.twitter.penguin.korean.v2.tokenizer.KoreanTokenizer$$anonfun$tokenize$1.apply(KoreanTokenizer.scala:254)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
        at scala.collection.immutable.List.flatMap(List.scala:344)
        at com.twitter.penguin.korean.v2.tokenizer.KoreanTokenizer$.tokenize(KoreanTokenizer.scala:254)
        at com.twitter.penguin.korean.v2.TwitterKoreanProcessor$.tokenize(TwitterKoreanProcessor.scala:49)
        at com.twitter.penguin.korean.v2.TwitterKoreanProcessor.tokenize(TwitterKoreanProcessor.scala)
        at com.twitter.common_internal.text.tokenizer.korean.TwitterKoreanTextTokenizerV2.reset(TwitterKoreanTextTokenizerV2.java:117)
        at com.twitter.common.text.token.TwitterTokenStream.reset(TwitterTokenStream.java:96)
        at com.twitter.common_internal.text.tokenizer.TokenStreamSwitcher.reset(TokenStreamSwitcher.java:25)
        at com.twitter.common.text.token.TwitterTokenStream.reset(TwitterTokenStream.java:96)
        at com.twitter.common.text.token.TokenProcessor.reset(TokenProcessor.java:48)
        at com.twitter.common.text.token.TwitterTokenStream.reset(TwitterTokenStream.java:96)
        at com.twitter.common.text.token.TokenProcessor.reset(TokenProcessor.java:48)
        at com.twitter.common.text.token.TwitterTokenStream.reset(TwitterTokenStream.java:96)
        at com.twitter.common.text.combiner.ExtractorBasedTokenCombiner.reset(ExtractorBasedTokenCombiner.java:57)
        at com.twitter.common.text.token.TokenProcessor.reset(TokenProcessor.java:48)
        at com.twitter.common.text.token.TwitterTokenStream.reset(TwitterTokenStream.java:96)
        at com.twitter.common.text.combiner.ExtractorBasedTokenCombiner.reset(ExtractorBasedTokenCombiner.java:57)
        at com.twitter.common.text.token.TokenProcessor.reset(TokenProcessor.java:48)
        at com.twitter.common.text.token.TwitterTokenStream.reset(TwitterTokenStream.java:96)
        at com.twitter.common.text.combiner.ExtractorBasedTokenCombiner.reset(ExtractorBasedTokenCombiner.java:57)
        at com.twitter.common.text.token.TokenProcessor.reset(TokenProcessor.java:48)
        at com.twitter.common.text.token.TwitterTokenStream.reset(TwitterTokenStream.java:96)
        at com.twitter.common.text.combiner.ExtractorBasedTokenCombiner.reset(ExtractorBasedTokenCombiner.java:57)
        at com.twitter.common.text.token.TokenProcessor.reset(TokenProcessor.java:48)
        at com.twitter.common.text.token.TwitterTokenStream.reset(TwitterTokenStream.java:96)
        at com.twitter.common.text.combiner.ExtractorBasedTokenCombiner.reset(ExtractorBasedTokenCombiner.java:57)
        at com.twitter.common.text.token.TokenProcessor.reset(TokenProcessor.java:48)
        at com.twitter.common.text.token.TwitterTokenStream.reset(TwitterTokenStream.java:96)
        at com.twitter.common.text.combiner.ExtractorBasedTokenCombiner.reset(ExtractorBasedTokenCombiner.java:57)
        at com.twitter.common.text.token.TokenProcessor.reset(TokenProcessor.java:48)
        at com.twitter.common.text.token.TwitterTokenStream.reset(TwitterTokenStream.java:96)
        at com.twitter.common.text.token.TokenProcessor.reset(TokenProcessor.java:48)
        at com.twitter.common.text.token.TwitterTokenStream.reset(TwitterTokenStream.java:96)
        at com.twitter.common.text.combiner.ExtractorBasedTokenCombiner.reset(ExtractorBasedTokenCombiner.java:57)
        at com.twitter.common.text.token.TokenProcessor.reset(TokenProcessor.java:48)
        at com.twitter.common.text.token.TwitterTokenStream.reset(TwitterTokenStream.java:96)
        at com.twitter.common.text.combiner.ExtractorBasedTokenCombiner.reset(ExtractorBasedTokenCombiner.java:57)
        at com.twitter.common.text.token.TokenProcessor.reset(TokenProcessor.java:48)
        at com.twitter.common.text.token.TwitterTokenStream.reset(TwitterTokenStream.java:96)
        at com.twitter.common.text.token.TokenProcessor.reset(TokenProcessor.java:48)
        at com.twitter.common.text.token.TwitterTokenStream.reset(TwitterTokenStream.java:96)
        at com.twitter.common.text.token.TokenProcessor.reset(TokenProcessor.java:48)
        at com.twitter.common.text.token.TwitterTokenStream.reset(TwitterTokenStream.java:96)
        at com.twitter.common.text.combiner.ExtractorBasedTokenCombiner.reset(ExtractorBasedTokenCombiner.java:57)
        at com.twitter.common.text.token.TokenProcessor.reset(TokenProcessor.java:48)
        at com.twitter.common.text.token.TwitterTokenStream.reset(TwitterTokenStream.java:96)
        at com.twitter.common.text.token.TokenProcessor.reset(TokenProcessor.java:48)
        at com.twitter.common.text.token.TwitterTokenStream.reset(TwitterTokenStream.java:96)
        at com.twitter.common.text.token.TokenizedCharSequenceStream.reset(TokenizedCharSequenceStream.java:132)
        at com.twitter.common.text.token.TokenizedCharSequence.createFrom(TokenizedCharSequence.java:346)
        at com.twitter.common_internal.text.pipeline.TwitterTextTokenizer.tokenize(TwitterTextTokenizer.java:156)
        at com.twitter.cortex.util.PenguinTweetTokenizer.tokens(TweetTokenizer.scala:45)
        at com.twitter.cortex.util.PenguinTweetTokenizer.hashtags(TweetTokenizer.scala:50)
        at com.twitter.cortex.datatypes.Status$.apply(Status.scala:157)

**Comment by jhsbeat** [comment]
@nlpenguin We're evaluating this analyzer for our product. Could you please let me know when do you plan to solve this issue? :)

**Comment by nlpenguin** [comment]
Oh sorry, i will get this done by this Friday. Thanks :)
On Tue, Nov 10, 2015 at 1:52 AM Hosang Jeon <notifications@github.com>
wrote:

> @nlpenguin <https://github.com/nlpenguin> We're evaluating this analyzer
> for our product. Could you please let me know when do you plan to solve
> this issue? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/twitter-korean-text/issues/79#issuecomment-155373334>
> .
>
-- 
Will Hohyon Ryu
유호현
Senior Software Engineer at Twitter

**Comment by tglstory** [comment]
What is the sample data that can reproduce this?

**Comment by nlpenguin** [comment]
@tglstory Not sure. That's why more debug feature is added. It was a bug in a scalding job.
